### ISSUE TITLE
init problem

### ISSUE THREAD

**Issue by smolleyes** [guillaume86/media-library#1]
hi 

your library seems great but can t use it, when i run the demo code (some typo errors in it)

i have 

```

sylvain@sylvain-pc:~/Documents/projets$ node --harmony t.js 
{ options: 
   { databasePath: './test',
     paths: [ '/home/sylvain/Documents/projets/nodio/public/audio' ] },
  db: 
   { inMemoryOnly: true,
     autoload: true,
     filename: null,
     persistence: { db: [Circular], inMemoryOnly: true, filename: null },
     executor: { buffer: [], ready: true, queue: [Object] },
     indexes: { _id: [Object] } } }
/home/sylvain/Documents/projets/t.js:11
library.scan().then(function() {
               ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/sylvain/Documents/projets/t.js:11:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

why this error and why no persistence on the db ? 

thanks

**Comment by smolleyes** [comment]
ok

strange to make so many errors in your demo with a good lib like this :)

in your error you need to change

databasePath by  dataPath: './'

and the code do not work with then ...

medialib.scan(function(err,data) {
medialib.tracks(function(err,tracks) {
            console.log(tracks);
  });
});

works

**Comment by guillaume86** [comment]
Sorry I don't have time to look into that at the moment, the readme is
probably outdated, the tests should be a better help if my memory is right.

2015-11-03 0:06 GMT+01:00 smolleyes notifications@github.com:

**Comment by smolleyes** [comment]
hello

np :) all tests are right yes 

if you can convert everything for co/koa it s a reallllllllllllllllllllllly great library ! 

i m learning es6 now and will try to make something ( et je dis bien essayer :p)!!

++
