### ISSUE TITLE
AssertionError: number too large

### ISSUE THREAD

**Issue by vankasteelj** [guillaume86/media-library#2]
When I test on a small folder with 8 songs, it works perfectly. 

When trying my entire library, I have this: 

> Uncaught AssertionError: number too large
> - at `media-library\node_modules\musicmetadata\node_modules\int53\index.js:53:3` 
> - coming from `media-library\node_modules\musicmetadata\node_modules\through\index.js:14:43`

and a bunch of those: 

> metadata parser error 
> Could not find metadata header
> - at `media-library\node_modules\musicmetadata\lib\id3v1.js:13:19`
> - coming from `media-library\lib\musicindexer.js:68`

**Comment by guillaume86** [comment]
Hi, 

For the first error you can report this to https://github.com/leetreveil/musicmetadata (it's the lib I use to read tags).
The second error is just a console.error I use while debugging you can comment it out if it bothers you.

**Comment by vankasteelj** [comment]
@guillaume86 the first error has been corrected but you're using an outdated 'musicmetadata' (0.4.6 instead of 2.0.2). Can you reopen this?

**Comment by guillaume86** [comment]
Do you have the latest version? I checked the package.json and the musicmetadata package should be up to date.

**Comment by vankasteelj** [comment]
I have the npm version, which is 1.2.1, and musicmetadata is 0.4.6. See: 

```
media-library@1.2.1 node_modules\media-library
├── lodash@2.4.2
├── filewalker@0.1.2 (fqueue@0.0.0)
├── musicmetadata@0.4.6 (int53@0.2.3, buffer-equal@0.0.0, filereader-stream@0.0.1, deep-equal@0.1.2, node-bitarray@0.0.2, through@2.3.8, strtok2@1.0.1)
└── nedb@0.10.11 (async@0.2.10, binary-search-tree@0.2.4, underscore@1.4.4, mkdirp@0.3.5)
```

**Comment by vankasteelj** [comment]
Ok yes, I understand now, you havent pushed 1.2.2, 1.2.3 and 1.2.4 to NPM. 

Unrelated, but I also noticed that your readme has a typo:

```
var MediaLibary = require('media-library');
var library = new MediaLibrary({ ...
```

`MediaLibRary` it should be.

**Comment by guillaume86** [comment]
Ok something must be broken with the travis pusblishing, I published it manually you should be able to get it in a few minutes.

**Comment by guillaume86** [comment]
Thanks I'll check that too.

2016-01-05 20:39 GMT+01:00 Jean van Kasteel notifications@github.com:

**Comment by vankasteelj** [comment]
Thanks, the issue is no longer present in 1.2.4, as expected.

There's a little thing you might do (or maybe I'll PR, I don't know yet), it's to add something like:

```
library.scan(true)
  .on('done', ...
```

with the `scan(true)` being `debug` and to report or not the 'debug' errors (like the "Could not find metadata header"), and ofc `scan()` or `scan(false)` being silent (unless real error).

But that's a minor improvement suggestion. Thanks anyway
